apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service
  namespace: services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:privileged
subjects:
  - kind: ServiceAccount
    name: signalfx-agent
    namespace: default
